

name: Android CI Bionic

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install glslangValidator
      run: sudo apt-get update && sudo apt-get install -y glslang-tools
      
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Attach release in action
      uses: actions/upload-artifact@v4
      with:
       name: Winlator Bionic apk
       path: ./app/build/outputs/apk/debug/app-debug.apk

    - name: "Get Short SHA"
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: "Get Version"
      run: echo "VERSION=$(echo $(cat app/build.gradle.kts | grep versionName | cut -d "=" -f 2 | sed "s/\"//g"))" >> $GITHUB_ENV

    - name: "List files"
      run: |
        ls -la app/src/main/assets


    
